### ISSUE TITLE
Don't open

### ISSUE THREAD

**Issue by Andyta2016** [Admiral-Fish/CitraRNG#20] opened 2023-05-01 09:06 UTC
![Error](https://user-images.githubusercontent.com/22484314/235432712-bc118eb1-a587-4067-89e0-f3b36d318108.png)

Each time I tried to open, console shows this error. I have Pyton 2.7 and 3.10, but I launch script with 3.10

**Comment by Admiral-Fish** [comment] 2023-05-01 19:59
Duplicate of #19

**Closed as not planned by Admiral-Fish** 2023-05-01 19:59 UTC
